# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  Exclude:
    - "db/migrate/*.rb"
    - "bin/*"
    - "db/schema.rb"
    - "config/puma.rb"
  NewCops: enable

Layout/IndentationWidth:
  Width: 4

Layout/LineLength:
  Enabled: false

Metrics:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false
